# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/predator/Documents/Project/temp/libviface

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/predator/Documents/Project/temp/libviface

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all:
	@./src/face.sh 1200 "libviface"
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named viface

# Build rule for target.
viface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viface
.PHONY : viface

# fast build rule for target.
viface/fast:
	$(MAKE) -f src/CMakeFiles/viface.dir/build.make src/CMakeFiles/viface.dir/build
.PHONY : viface/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f test/CMakeFiles/tests.dir/build.make test/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named basic

# Build rule for target.
basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic
.PHONY : basic

# fast build rule for target.
basic/fast:
	$(MAKE) -f examples/basic/CMakeFiles/basic.dir/build.make examples/basic/CMakeFiles/basic.dir/build
.PHONY : basic/fast

#=============================================================================
# Target rules for targets named dispatch

# Build rule for target.
dispatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dispatch
.PHONY : dispatch

# fast build rule for target.
dispatch/fast:
	$(MAKE) -f examples/dispatch/CMakeFiles/dispatch.dir/build.make examples/dispatch/CMakeFiles/dispatch.dir/build
.PHONY : dispatch/fast

#=============================================================================
# Target rules for targets named signal

# Build rule for target.
signal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 signal
.PHONY : signal

# fast build rule for target.
signal/fast:
	$(MAKE) -f examples/signal/CMakeFiles/signal.dir/build.make examples/signal/CMakeFiles/signal.dir/build
.PHONY : signal/fast

#=============================================================================
# Target rules for targets named timeout

# Build rule for target.
timeout: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timeout
.PHONY : timeout

# fast build rule for target.
timeout/fast:
	$(MAKE) -f examples/timeout/CMakeFiles/timeout.dir/build.make examples/timeout/CMakeFiles/timeout.dir/build
.PHONY : timeout/fast

#=============================================================================
# Target rules for targets named stats

# Build rule for target.
stats: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stats
.PHONY : stats

# fast build rule for target.
stats/fast:
	$(MAKE) -f examples/stats/CMakeFiles/stats.dir/build.make examples/stats/CMakeFiles/stats.dir/build
.PHONY : stats/fast

#=============================================================================
# Target rules for targets named threads

# Build rule for target.
threads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 threads
.PHONY : threads

# fast build rule for target.
threads/fast:
	$(MAKE) -f examples/threads/CMakeFiles/threads.dir/build.make examples/threads/CMakeFiles/threads.dir/build
.PHONY : threads/fast

#=============================================================================
# Target rules for targets named vifaced

# Build rule for target.
vifaced: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vifaced
.PHONY : vifaced

# fast build rule for target.
vifaced/fast:
	$(MAKE) -f examples/vifaced/CMakeFiles/vifaced.dir/build.make examples/vifaced/CMakeFiles/vifaced.dir/build
.PHONY : vifaced/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... viface"
	@echo "... tests"
	@echo "... basic"
	@echo "... dispatch"
	@echo "... signal"
	@echo "... timeout"
	@echo "... stats"
	@echo "... threads"
	@echo "... vifaced"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

